services:
  db:
    image: postgres:15-alpine
    container_name: tournament-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tournament_db
      - POSTGRES_USER=tournament_user
      - POSTGRES_PASSWORD=tournament_pass

  django:
    build: .
    container_name: tournament-api
    entrypoint: ["bash", "/app/docker-entrypoint.sh"]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:8000:8000"
    env_file:
      - .env.test
    depends_on:
      - db
volumes:
  postgres-data:
